name: Telegram Scalping Bot

on:
  schedule:
    - cron: "*/10 * * * *"   # toutes les 10 minutes
  workflow_dispatch:       # exécution manuelle possible

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run scalping bot
        run: python3 main.py

